revoke execute on function public.set_updated_at() from public;
revoke execute on function public.generate_join_code() from public;
revoke execute on function public.build_lobby_state(uuid) from public;
revoke execute on function public.random_int_between(integer, integer) from public;
revoke execute on function public.get_board_cell_config(text) from public;
revoke execute on function public.get_board_cell_ids(text) from public;
revoke execute on function public.get_next_turn_player_id(uuid, uuid) from public;
revoke execute on function public.is_deal_cell(text) from public;
revoke execute on function public.get_deal_cell_params(text) from public;
revoke execute on function public.create_deal_pending_action(uuid, uuid) from public;
revoke execute on function public.is_client_cell(text) from public;
revoke execute on function public.get_client_cell_params(text) from public;
revoke execute on function public.create_client_pending_action(uuid, uuid) from public;
revoke execute on function public.get_tender_cell_params(text) from public;
revoke execute on function public.is_tender_cell(text) from public;
revoke execute on function public.ensure_game_tenders(uuid) from public;
revoke execute on function public.build_game_tenders_state(uuid) from public;
revoke execute on function public.resolve_tender_landing(uuid, uuid) from public;
revoke execute on function public.get_company_cell_params(text) from public;
revoke execute on function public.is_company_cell(text) from public;
revoke execute on function public.ensure_game_companies(uuid) from public;
revoke execute on function public.build_game_companies_state(uuid) from public;
revoke execute on function public.resolve_company_landing(uuid, uuid) from public;
revoke execute on function public.get_director_cell_params(text) from public;
revoke execute on function public.is_director_cell(text) from public;
revoke execute on function public.build_game_directors_state(uuid) from public;
revoke execute on function public.get_outer_entry_cell_id() from public;

grant execute on function public.create_game(integer, text) to authenticated;
grant execute on function public.join_game(text, text) to authenticated;
grant execute on function public.start_game(uuid) to authenticated;
grant execute on function public.roll_dice(uuid) to authenticated;
grant execute on function public.resolve_cell_basic(uuid, uuid) to authenticated;
grant execute on function public.resolve_deal(uuid, text) to authenticated;
grant execute on function public.resolve_client(uuid, text, integer) to authenticated;
grant execute on function public.resolve_tender(uuid, text) to authenticated;
grant execute on function public.resolve_company(uuid, integer) to authenticated;
grant execute on function public.resolve_director(uuid, uuid) to authenticated;
grant execute on function public.elect_ceo(uuid) to authenticated;
grant execute on function public.ring_transition(uuid, text) to authenticated;
grant execute on function public.handle_debt(uuid, uuid) to authenticated;
